# Generated by Django 4.0.3 on 2022-03-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=50)),
                ('productURL', models.URLField()),
                ('productPrice', models.FloatField()),
                ('productDiscount', models.FloatField()),
                ('productDescription', models.TextField()),
            ],
        ),
    ]
