# Generated by Django 4.0.3 on 2022-05-04 04:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_id_remove_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
