# Generated by Django 4.0.3 on 2022-05-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_productid_alter_user_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productURL',
            field=models.URLField(max_length=500),
        ),
    ]
