# Generated by Django 4.0.3 on 2022-05-13 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_cartitem_cartid_remove_cartitem_productid_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Customer',
        ),
    ]
